/**
 * Client-side export utilities — focused on counting & classification.
 */

function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ── CSV export ─────────────────────────────────────────────────────────────────
export function exportCSV(roiCounts, lineCounts) {
  const ts = new Date().toISOString().slice(0, 16).replace('T', '_').replace(/:/g, '-')
  let csv = ''

  // ROI counts
  csv += 'ROI Vehicle Counts\n'
  csv += 'Zone Name,Total Vehicles\n'
  Object.entries(roiCounts).forEach(([name, count]) => {
    csv += `"${name}",${count}\n`
  })

  // Line counts
  if (Object.keys(lineCounts).length > 0) {
    csv += '\nCounting Lines\n'
    csv += 'Line Name,Forward,Backward,Total\n'
    Object.entries(lineCounts).forEach(([name, data]) => {
      const fwd = data.total_fwd || 0
      const bwd = data.total_bwd || 0
      csv += `"${name}",${fwd},${bwd},${fwd + bwd}\n`
    })
  }

  downloadFile(csv, `traffic_counts_${ts}.csv`, 'text/csv')
}

// ── HTML report export ─────────────────────────────────────────────────────────
export function exportHTML(summary, rois) {
  const ts = new Date().toLocaleString()

  const roiRows = Object.entries(summary.roi_totals || {}).map(([name, data]) =>
    `<tr><td>${name}</td><td style="font-weight:700;color:#00e5a0">${data.total || 0}</td><td>${
      Object.entries(data.counts || {}).map(([k,v]) => `<span style="color:${
        {Car:'#44AAFF',Motorcycle:'#FF44FF',Bus:'#FFAA00',Truck:'#44FF44'}[k] || '#ccc'
      }">${k}: ${v}</span>`).join(' · ')
    }</td></tr>`
  ).join('')

  const lineRows = Object.entries(summary.line_totals || {}).map(([name, data]) =>
    `<tr><td>${name}</td><td>${data.total_fwd || 0}</td><td>${data.total_bwd || 0}</td><td style="font-weight:700">${(data.total_fwd||0)+(data.total_bwd||0)}</td></tr>`
  ).join('')

  const turnRows = Object.entries(summary.turning_movements || {}).map(([type, count]) =>
    `<tr><td>${type}</td><td>${count}</td><td>${summary.total_vehicles ? Math.round(count/summary.total_vehicles*100) : 0}%</td></tr>`
  ).join('')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Traffic Counting Report</title>
<style>
  body { font-family: 'Segoe UI', sans-serif; background: #0a0c0f; color: #e2e8f0; margin: 0; padding: 32px; }
  h1 { color: #00e5a0; font-family: monospace; }
  h2 { color: #8896aa; font-size: 14px; letter-spacing: 0.1em; text-transform: uppercase; margin-top: 32px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th { background: #181c22; color: #8896aa; font-size: 12px; padding: 10px 14px; text-align: left; }
  td { padding: 10px 14px; border-bottom: 1px solid #232830; font-size: 14px; }
  tr:hover td { background: #111418; }
  .stat { display:inline-block; padding: 20px 28px; background: #111418;
          border: 1px solid #232830; border-radius: 10px; margin: 0 12px 12px 0; }
  .stat-num { font-size: 36px; font-family: monospace; font-weight: 700; color: #00e5a0; }
  .stat-label { font-size: 12px; color: #8896aa; letter-spacing: 0.08em; }
  .footer { color: #4a5568; font-size: 12px; margin-top: 40px; }
</style>
</head>
<body>
<h1>Traffic Counting Report</h1>
<p style="color:#8896aa">Generated: ${ts}</p>

<div style="margin:20px 0">
  <div class="stat">
    <div class="stat-num">${summary.total_vehicles || 0}</div>
    <div class="stat-label">TOTAL VEHICLES</div>
  </div>
  <div class="stat">
    <div class="stat-num">${summary.duration_sec || 0}s</div>
    <div class="stat-label">DURATION</div>
  </div>
  <div class="stat">
    <div class="stat-num">${summary.total_frames || 0}</div>
    <div class="stat-label">FRAMES ANALYSED</div>
  </div>
</div>

<h2>Vehicle Counts by Zone</h2>
<table>
  <tr><th>Zone</th><th>Total</th><th>By Classification</th></tr>
  ${roiRows}
</table>

${lineRows ? `
<h2>Counting Lines</h2>
<table>
  <tr><th>Line</th><th>Forward</th><th>Backward</th><th>Total</th></tr>
  ${lineRows}
</table>` : ''}

<h2>Turning Movements</h2>
<table>
  <tr><th>Type</th><th>Count</th><th>Percentage</th></tr>
  ${turnRows}
</table>

<p class="footer">Generated by Traffic Monitor · ${ts}</p>
</body>
</html>`

  downloadFile(html, `traffic_counts_${ts.replace(/[/:, ]/g, '-')}.html`, 'text/html')
}
